trigger:
  branches:
    include: [dev]
pr:
  branches:
    include: [dev, test, prod]
pool:
  vmImage: ubuntu-latest
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
- script: |
    python -m pip install --upgrade pip
    pip install pytest
    cd tests
    pytest -q
  displayName: Run unit tests
